# Generated by Django 5.2 on 2025-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddonor',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
        migrations.AddField(
            model_name='fooddonor',
            name='expiry_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='fooddonor',
            name='food_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fooddonor',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fooddonor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fooddonor',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='username',
            field=models.CharField(default='-', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddonor',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
