# Generated by Django 5.2 on 2025-05-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_rename_name_fooddonor_password_remove_volunteer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.fooddonor'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name_food',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
