# Generated by Django 5.2 on 2025-05-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_fooditem_food_donor_alter_fooditem_name_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
