# Generated by Django 5.2 on 2025-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_fooddonor_user_volunteer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
