# Generated by Django 5.2 on 2025-05-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_alter_donationtransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransaction',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.volunteer'),
        ),
    ]
