# Generated by Django 5.2 on 2025-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_alter_donationtransaction_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Queued', 'Queued')], default='Pending', max_length=50),
        ),
    ]
