# Generated by Django 5.2 on 2025-05-21 05:42

import donation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_alter_donationtransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtransaction',
            name='delivery_evidence',
            field=models.ImageField(blank=True, null=True, upload_to=donation.models.DonationTransaction.delivery_evidence_upload_path),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=donation.models.FoodItem.food_image_upload_path),
        ),
    ]
